name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Use Node.js 16
       uses: actions/setup-node@v3
       with:
         node-version: 16
     - name: lint and test
       run: |
         yarn install
         yarn lint
         yarn test
      - run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEDDING_PHOTO_APP_3FB3E }}'
          channelId: live
          projectId: wedding-photo-app-3fb3e
